# Generated by Django 4.2.1 on 2023-06-04 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Specialization',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
