# Generated by Django 4.2.1 on 2023-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_email_attendance_status_a_email_attendance_status_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='total',
            field=models.FloatField(default=100),
        ),
    ]
