# Generated by Django 4.2.1 on 2023-06-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_email_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='period_one',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='email',
            name='period_three',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='email',
            name='period_two',
            field=models.FloatField(default=100),
        ),
    ]
