# Generated by Django 4.2.1 on 2023-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_remove_email_marks_email_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bus_code',
            field=models.IntegerField(default=100),
        ),
    ]
