# Generated by Django 4.2.1 on 2023-06-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_email_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
