# Generated by Django 4.2.1 on 2023-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_alter_email_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='math_mark',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='email',
            name='physics_mark',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='email',
            name='python_mark',
            field=models.FloatField(default=100),
        ),
    ]
