# Generated by Django 4.2.1 on 2023-06-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_alter_email_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='g',
            field=models.IntegerField(default=100),
        ),
    ]
