# Generated by Django 4.2.1 on 2023-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_bus_remove_email_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='g',
        ),
        migrations.AddField(
            model_name='bus',
            name='east',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='north',
            field=models.FloatField(default=100),
        ),
    ]
