# Generated by Django 4.2.1 on 2023-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_canteen', models.IntegerField(default=100)),
                ('password_canteen', models.CharField(default='password', max_length=100)),
            ],
        ),
    ]
