# Generated by Django 4.2.1 on 2023-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=1)),
                ('food_item', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(default=100)),
                ('quanity', models.IntegerField(default=1)),
            ],
        ),
    ]
